### ISSUE TITLE
Suggestion: Move title and weight of boxs directly into UI

### ISSUE THREAD

**Issue by cmaes** [EmilienDupont/planeLoading#1]
Right now you put the title (e.g. Large Box) and weight (e.g. 6 tonnes) in the text above the example. I'd move that title and weight directly into the UI, maybe above the representation of each box on the side. That way your eye can stay in the UI the whole time, and you don't need to read the text above the example to understand it.

**Comment by EmilienDupont** [comment]
Agreed and fixed.
